# Generated by Django 5.1 on 2024-09-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='About',
        ),
    ]
