# Generated by Django 5.1 on 2024-09-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_member_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phone',
        ),
    ]
